spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysqlstudy?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.10.177
    port: 6379
    password: 12345
  #kafka
  kafka:
    bootstrap-servers: 192.168.10.177:9092
    producer:
      #      生产者序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      #      消费者序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      消费者消费的group_id
      group-id: kafkaTest1

mybatis:
  type-aliases-package: com.lwy.demo.entity
  mapper-locations: mapper/*.xml
server:
  port: 9999

#es
elasticsearch:
  host: 127.0.0.1
  port: 9200

logging:
  level:
    com:
      liuweiyi:
        demo:
          es: debug



